apiVersion: v1
kind: Service
metadata:
  name: iam-server-service
spec:
  selector:
    app: iam-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 50051
    # Use LoadBalancer because NodePort gave us TCP Read Failed when a client tries to connect
  type: LoadBalancer
