apiVersion: v1
kind: Pod
metadata:
  name: iam-server-pod
  labels:
    app: iam-server
spec:
  containers:
    - name: iam-server
      image: shopinc/iam-server:0.0.1
      command: ['sh', '-c', 'echo Hello Kubernetes! && sleep 3600']
      envFrom:
      - secretRef:
          name: iam-secrets
